jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install Bun ğŸ”§
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "${HOME}/.bun/bin" >> $GITHUB_PATH

      - name: Install Dependencies with Bun ğŸ”§
        run: bun install

      - name: Build and Export with Next.js ğŸ—ï¸
        run: bun run next build && bun run next export

      - name: Check Build Output
        run: ls -la

      - name: Upload artifact ğŸ“¡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
